source 'http://rubygems.org'

gem 'rails', '3.0.10'
gem 'jquery-rails', '>= 1.0.12'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem "mysql"
gem 'blacklight', '3.0.0'
gem 'solrizer-fedora'

gem "rsolr", "1.0.2"  # there's a bug in 1.0.7
gem "hydra-head", "3.0.1"
gem 's3_swf_upload', :git => 'git://github.com/nathancolgate/s3-swf-upload-plugin'
gem "aws-s3"
gem "aws-sdk"
gem "haml"
gem "paperclip", "~> 2.4"

gem "om", "~> 1.4.3"
# gem "om", :git=>"git://github.com/mediashelf/om.git"

gem 'ruby-debug'
gem "rbx-require-relative", "0.0.5"

group :development, :test do
  gem 'rspec'
  gem 'rspec-rails'
  gem 'mocha'
  gem 'cucumber', '>=0.8.5'
  gem 'cucumber-rails'
  gem 'gherkin'
  gem "equivalent-xml", ">= 0.2.4"
end

group :importer do
 gem 'fastercsv'
end
gem "devise"
