development:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://localhost:8983/solr/development
test: &TEST
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://localhost:8983/solr/development
production:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@archives.ktgrinpoche.org:8080/fedora
  solr:
    url: http://archives.ktgrinpoche.org:8080/solr_marpa_foundation_archive
cucumber:
  <<: *TEST
