development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fedora
test: &TEST
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fedora-test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://archives.ktgrinpoche.org:8080/fedora
cucumber:
  <<: *TEST
