development:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://localhost:8983/solr/development
test: &TEST
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@127.0.0.1:8983/fedora
  solr:
    url: http://localhost:8983/solr/development
production:
  fedora:
    url: http://fedoraAdmin:fedoraAdmin@ec2-204-236-243-156.compute-1.amazonaws.com:8080/fedora
  solr:
    url: http://ec2-204-236-243-156.compute-1.amazonaws.com:8080/solr
cucumber:
  <<: *TEST
