uva-only:
  - uva-only
archivist:
  - arig
  - aekarr
  - rolmokhen
  - mzumwalt
  - archivist1
  - ecallahan
  - rtaylor
  - tsepakdorje
donor:
  - donor1
researcher:
  - researcher1
patron:
  - patron1

