archivist:
  - archivist@example.com
  - archivist1@example.com
donor:
  - donor@example.com
researcher:
  - researcher@example.com
patron:
  - patron@example.com
admin_policy_object_editor:
  - archivist@example.com
