development: &DEFAULT 
  bucket: marpa-dev-uploads
  access_key_id: 1RH3E9DNJ81GYNCCX5G2
  secret_access_key: 9iP8y4mSKWspf2vWPBU3P+zoyGT9752P5y/rHLoY
test:
  bucket: marpa-test-uploads
  access_key_id: 1RH3E9DNJ81GYNCCX5G2
  secret_access_key: 9iP8y4mSKWspf2vWPBU3P+zoyGT9752P5y/rHLoY
production: 
  bucket: marpa-uploads
  access_key_id: 1RH3E9DNJ81GYNCCX5G2
  secret_access_key: 9iP8y4mSKWspf2vWPBU3P+zoyGT9752P5y/rHLoY
default:
  <<: *DEFAULT
