marpa: &DEFAULT 
  access_key_id: 1RH3E9DNJ81GYNCCX5G2
  secret_access_key: 9iP8y4mSKWspf2vWPBU3P+zoyGT9752P5y/rHLoY
mila:
  access_key_id: 2010203290392
  secret_access_key: boo
default:
  <<: *DEFAULT