# This is a sample config file that does not have multiple solr instances. You will also need to be sure to
# edit the fedora.yml file to match the solr URL for active-fedora. 
development:
  url: http://localhost:8983/solr/development
test: &TEST
  url: http://127.0.0.1:8983/solr/development
cucumber:
  <<: *TEST
production:
  url: http://ec2-204-236-243-156.compute-1.amazonaws.com:8080/solr/development
