development:
  default:
    url: http://archives.ktgrinpoche.org:8983/solr/developments
  fulltext:
    url: http://archives.ktgrinpoche.org:8983/solr/development
test: &TEST
  default:
    url: http://archives.ktgrinpoche.org:8983/solr/test
  fulltext:
    url: http://archives.ktgrinpoche.org:8983/solr/test
production:
  default:
    url: http://your.production.server:8080/bl_solr/core0 
  fulltext:
    url: http://your.production.server:8080/bl_solr/core1
cucumber:
  <<: *TEST
cucumber:
  <<: *TEST
